$(document).ready(function(){
    $(".sub").hide();
    $(".nav_back").hide();
    $(".top_nav").mouseenter(function(){
        $(".sub").stop().slideDown(100);
        $(".nav_back").stop().slideDown(100);
    })
    $(".top_nav").mouseleave(function(){
        $(".sub").stop().slideUp(100);
        $(".nav_back").stop().slideUp(100);
    })
})